.NET Core 3.0 (#83)
* Updated dependencies

* netcoreapp3.0

* SpecialFunctions call into native code on win and linux

Previously it was only linux. Benchmark show that on win the native version is also faster.

* Updated CircleCI and build.sh

* Updated AppVeyor image to VS 2019 Preview

There is .NET Core 3.0 SDK (preview), https://www.appveyor.com/updates/2018/12/13/

* Tests with netcoreapp2.0 instead of net471

When building on linux (mono) these strange errors occur:
```
error CS0012: The type 'ValueType' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
```

* Nit Spacing

Cf. https://github.com/gfoidl/Stochastics/pull/83#discussion_r273036963

* CircleCI build image adapted

Cf. https://github.com/gfoidl/Stochastics/pull/83#discussion_r273036122

* Simplified Strings.resx / ThrowHelper

* Drop HW-intrinsics for .NET Core 2.1

Cf. https://github.com/gfoidl/Stochastics/pull/83#issuecomment-480843219